#!/usr/bin/env python3
"""The cross-site footer, generated from the registry.

    scripts/render_footer.py --self emulators            # print it
    scripts/render_footer.py --self emulators --write    # inject into site/index.html
    scripts/render_footer.py --self emulators --check    # exit 1 if stale

WHY IT IS GENERATED. Eleven published sites, each wanting a link and a tagline
for the other ten: 110 links maintained by hand, in eleven files, in eleven
repositories. That is not a footer, it is a promise to go stale. Every entry
here comes from `members.json`, which is the same file the map, the tables and
llms.txt are generated from, so a site added to the ecosystem appears in every
footer at once.

WHY STATIC HTML AND NOT A FETCH. The obvious alternative is to publish one JSON
from the hub and have each footer render itself in the browser. It would be a
single source with no sweep at all -- and it would defeat half the point.
Cross-linking eleven sites on one origin is exactly what makes them findable,
and a link a crawler never sees is not a link. So the markup is committed and
the freshness is a CI check rather than a runtime fetch.

WHY `--self`. The footer on a site does not link to that site: eleven entries,
one of which is where you already are, reads as a mistake. The current site is
rendered as plain text rather than dropped, so every footer shows the whole
family and the reader can see where they are in it.

TAGLINE, NOT ROLE. `role` in the registry is a descriptor written for the
registry -- `emulators` reads "This repo: the ecosystem directory", which is
wrong on any other site's page. `tagline` is the reader-facing one and `role`
is the fallback.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "members.json"
LANDING = ROOT / "site" / "index.html"
BEGIN = "<!-- BEGIN family-footer (generated by scripts/render_footer.py) -->"
END = "<!-- END family-footer -->"

# The order a reader meets them, and the heading each group gets. Tiers with no
# published site never appear, so leaves and platforms are absent by
# construction rather than by exclusion.
GROUPS = [
    ("emulator", "The emulators"),
    ("composition", "The certified set"),
    ("application", "Built on the family"),
    ("hub", "The directory"),
]


def members() -> list[dict]:
    return json.loads(REGISTRY.read_text(encoding="utf-8"))["members"]


def sites(all_members: list[dict]) -> list[dict]:
    """Only members that publish somewhere a reader can go."""
    return [m for m in all_members if m.get("docs")]


def render(all_members: list[dict], self_name: str) -> str:
    published = sites(all_members)
    if self_name not in {m["name"] for m in published}:
        raise SystemExit(
            f"render_footer: --self {self_name!r} is not a member with a docs "
            f"site. Known: {', '.join(sorted(m['name'] for m in published))}"
        )

    by_tier: dict[str, list[dict]] = {}
    for m in published:
        by_tier.setdefault(m["tier"], []).append(m)
    placed = {t for t, _ in GROUPS}
    missing = sorted(set(by_tier) - placed)
    if missing:
        raise SystemExit(
            f"render_footer: {missing} publish a site and this footer places no "
            f"group for them. Add one rather than letting a site go unlinked."
        )

    out = [BEGIN, '<nav class="family" aria-label="The rest of the family">',
           "  <p class=\"family-lede\">Eleven documentation sites, one ecosystem. "
           "Every emulator grades itself in a parity ledger, and every green claim "
           "names the test that proves it.</p>"]
    for tier, heading in GROUPS:
        group = sorted(by_tier.get(tier, []), key=lambda m: m["name"])
        if not group:
            continue
        out.append(f'  <div class="family-group">')
        out.append(f"    <h3>{html.escape(heading)}</h3>")
        out.append("    <ul>")
        for m in group:
            tag = html.escape(m.get("tagline") or m.get("role") or "")
            name = html.escape(m["name"])
            if m["name"] == self_name:
                out.append(
                    f'      <li class="here"><span class="name">{name}</span>'
                    f'<span class="what">{tag}</span>'
                    f'<span class="you">you are here</span></li>'
                )
            else:
                out.append(
                    f'      <li><a href="{html.escape(m["docs"])}">'
                    f'<span class="name">{name}</span>'
                    f'<span class="what">{tag}</span></a></li>'
                )
        out.append("    </ul>")
        out.append("  </div>")
    out.append("</nav>")
    out.append(END)
    return "\n".join(out)


def inject(page: str, block: str) -> str:
    if BEGIN in page and END in page:
        return re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block,
                      page, flags=re.S)
    # First time: INSIDE the footer's container, not after it. These pages wrap
    # their content in `<div class="wrap">` for the page's max-width and
    # padding; appending before `</footer>` lands after that div closes, and the
    # block renders full-bleed against inset text above it. Measured by looking
    # at it, which is the only way that kind of thing shows up.
    m = re.search(r"(<footer[^>]*>.*?)(\s*</div>\s*</footer>)", page, re.S)
    if m:
        return page[: m.end(1)] + "\n" + block + page[m.start(2) :]
    for anchor in ("</footer>", "</body>"):
        if anchor in page:
            i = page.rindex(anchor)
            return page[:i] + block + "\n" + page[i:]
    raise SystemExit("render_footer: the landing page has no </footer> or </body>")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--self", dest="self_name", required=True)
    p.add_argument("--write", action="store_true")
    p.add_argument("--check", action="store_true")
    a = p.parse_args()

    block = render(members(), a.self_name)
    if not (a.write or a.check):
        print(block)
        return 0
    if not LANDING.is_file():
        raise SystemExit(f"render_footer: no landing page at {LANDING}")
    page = LANDING.read_text(encoding="utf-8")
    want = inject(page, block)
    if a.write:
        LANDING.write_text(want, encoding="utf-8")
        print(f"footer: wrote {LANDING.relative_to(ROOT)}")
        return 0
    if page != want:
        print("footer: site/index.html is stale. Run --write", file=sys.stderr)
        return 1
    print("footer: site/index.html matches the registry")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
