#!/usr/bin/env python3
"""Render the matrix tables in README.md and /docs from members.json.

These tables were hand-maintained, and it went wrong twice in one sitting:
first from a survey of local checkouts that were sitting on working branches,
then from trusting README prose that says "Reserved. It holds nothing but this
file and a LICENSE" over a tree carrying fifty-two files. The registry is
derived from what is on main, and generating from it means the three copies of
the table cannot drift from each other or from the source.

  ./scripts/render_tables.py            rewrite the tables in place
  ./scripts/render_tables.py --check    exit 1 if any file is out of date
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "members.json"
BEGIN = "<!-- BEGIN matrix (generated by scripts/render_tables.py) -->"
END = "<!-- END matrix -->"

ENGINES = [("fabric", "Fabric"), ("databricks", "Databricks"), ("snowflake", "Snowflake")]
ORCH = [
    ("airflow3", "Airflow 3"),
    ("notebook-pipelines", "Notebooks + Data Pipelines"),
    ("airflow-builtin", "Built-in Airflow"),
    ("jobs", "Databricks Jobs"),
    ("tasks", "Snowflake Tasks"),
]
ORDER = [
    ("fabric", "airflow3"), ("fabric", "notebook-pipelines"), ("fabric", "airflow-builtin"),
    ("databricks", "jobs"), ("databricks", "airflow3"),
    ("snowflake", "tasks"), ("snowflake", "airflow3"),
]


def load():
    members = json.loads(REGISTRY.read_text())["members"]
    idx = {}
    for m in members:
        if m["tier"] in ("leaf", "platform"):
            idx[(m["tier"], m["engine"], m["orchestrator"])] = m
    return members, idx


def cell(m, label):
    if m is None:
        return "?"
    mark = "✅" if m["status"] == "built" else "⬜"
    url = f"https://github.com/calvinchengx/{m['name']}"
    return f"{mark} [{label}](url)".replace("url", url)


def table(idx, short):
    """short=True uses 'leaf'/'platform' as the link text (README), otherwise
    the full repo name (docs), matching how each file already read."""
    rows = ["| Engine | Orchestrator | Leaf product | Platform |", "|---|---|---|---|"]
    eng = dict(ENGINES)
    orch = dict(ORCH)
    for e, o in ORDER:
        leaf = idx.get(("leaf", e, o))
        plat = idx.get(("platform", e, o))
        rows.append(
            f"| {eng[e]} | {orch[o]} "
            f"| {cell(leaf, 'leaf' if short else leaf['name'])} "
            f"| {cell(plat, 'platform' if short else plat['name'])} |")
    return "\n".join(rows)


def legend(members):
    no_ci = [m["name"] for m in members if m["ci"] == "missing"]
    out = ["", "✅ built · ⬜ reserved, holding a README and a LICENSE", ""]
    if no_ci:
        out += [
            f"{len(no_ci)} built repos have **no CI at all** and nothing verifies them: "
            + ", ".join(f"`{n}`" for n in no_ci) + ". See",
            "[CI status](08-ci-status.md) for the live sweep across every member.",
            "",
        ]
    return "\n".join(out)


def block(members, idx, short):
    return f"{BEGIN}\n\n{table(idx, short)}\n{legend(members)}\n{END}"


TARGETS = [
    (ROOT / "README.md", True),
    (ROOT / "docs" / "01-the-map.md", False),
    (ROOT / "docs" / "03-the-data-product-matrix.md", False),
]


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="verify the committed tables match the registry")
    a = ap.parse_args()

    members, idx = load()
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    stale = []
    for path, short in TARGETS:
        src = path.read_text()
        if BEGIN not in src:
            print(f"{path.name}: missing the generated-block markers", file=sys.stderr)
            return 2
        want = block(members, idx, short)
        # The README links to the site page by URL, /docs links by relative path.
        if short:
            want = want.replace("(08-ci-status.md)",
                                "(https://calvinchengx.github.io/emulators/08-ci-status/)")
        new = pattern.sub(lambda _: want, src)
        if new == src:
            continue
        stale.append(path.name)
        if not a.check:
            path.write_text(new)

    if a.check and stale:
        print("out of date with members.json: " + ", ".join(stale), file=sys.stderr)
        print("run ./scripts/render_tables.py", file=sys.stderr)
        return 1
    print(("would rewrite: " if a.check else "rewrote: ") + (", ".join(stale) or "nothing"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
