#!/usr/bin/env python3
"""Render the evidence table in docs/05 from azure-emulators' family_parity.py.

The table was hand-copied, and it went stale within four hours of being
written: a databricks witness landed and the page read 28/30 (93%) while the
generator said 29/30 (97%). The page's own text tells readers to run the
script rather than trust the page, which is an admission that a hand-copied
number is a claim about the past.

The numbers are NOT recomputed here. family_parity.py in azure-emulators is
the one implementation, it derives its counts using each repo's own checker
rules, and a second implementation would be a second answer to the same
question. This shells out to it and pastes the result.

  ./scripts/render_evidence.py                  clone azure-emulators, rewrite
  ./scripts/render_evidence.py --local ../azure-emulators
  ./scripts/render_evidence.py --check          exit 1 if the doc is stale
"""
import argparse
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "docs" / "05-why-these-emulators.md"
BEGIN = "<!-- BEGIN evidence (generated by scripts/render_evidence.py) -->"
END = "<!-- END evidence -->"
UPSTREAM = "https://github.com/calvinchengx/azure-emulators"


def parity_table(repo: Path) -> str:
    """Run family_parity.py --evidence and return just the markdown table."""
    script = repo / "scripts" / "family_parity.py"
    if not script.exists():
        raise SystemExit(f"no family_parity.py at {script}")
    p = subprocess.run([sys.executable, str(script), "--evidence"],
                       cwd=repo, capture_output=True, text=True)
    if p.returncode != 0:
        raise SystemExit(f"family_parity.py failed: {p.stderr.strip()[:400]}")
    rows = [l for l in p.stdout.splitlines() if l.startswith("|")]
    if len(rows) < 4:
        # Fewer than a header, a separator and two members means the output
        # shape changed. Pasting it anyway would publish an empty table under
        # a confident heading.
        raise SystemExit(f"family_parity.py produced {len(rows)} table rows, "
                         f"expected a header plus one per emulator")
    body = [r for r in rows[2:] if not r.startswith("| **")]
    if not any("%" in r for r in body):
        raise SystemExit("no percentage found in the table body; the "
                         "generator's output format changed")
    return "\n".join(rows)


def block(table: str) -> str:
    return (
        f"{BEGIN}\n\n{table}\n\n"
        "Generated by `scripts/render_evidence.py` from azure-emulators'\n"
        "`family_parity.py`, which derives each count using that repo's own\n"
        "checker rules. The numbers move whenever a witness lands, so run it\n"
        "yourself rather than trusting this snapshot:\n\n"
        "```sh\n"
        "git clone https://github.com/calvinchengx/azure-emulators\n"
        "cd azure-emulators && ./scripts/family_parity.py --evidence\n"
        "```\n\n"
        f"{END}")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--local", metavar="PATH",
                    help="use an existing azure-emulators checkout")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    if a.local:
        table = parity_table(Path(a.local).expanduser().resolve())
    else:
        with tempfile.TemporaryDirectory() as tmp:
            dest = Path(tmp) / "azure-emulators"
            r = subprocess.run(["git", "clone", "--depth", "1", "-q", UPSTREAM, str(dest)],
                               capture_output=True, text=True)
            if r.returncode != 0:
                raise SystemExit(f"clone failed: {r.stderr.strip()[:300]}")
            table = parity_table(dest)

    src = DOC.read_text()
    if BEGIN not in src:
        raise SystemExit(f"{DOC.name}: missing the generated-block markers")
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END),
                 lambda _: block(table), src, flags=re.S)

    if new == src:
        print("evidence table is up to date")
        return 0
    if a.check:
        print(f"{DOC.name} is stale against family_parity.py", file=sys.stderr)
        print("run ./scripts/render_evidence.py", file=sys.stderr)
        return 1
    DOC.write_text(new)
    print(f"rewrote the evidence table in {DOC.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
