#!/usr/bin/env python3
"""The numbers the landing page shows, computed rather than typed.

    scripts/site_data.py --out _site        # write _site/site-data.json
    scripts/site_data.py                    # print it

WHY. `site/index.html` is a marketing page, and a marketing page is the last
thing anyone re-reads. Every count on it is a fact about the ecosystem that
moves without anyone thinking of it as a number: this repository has already
shipped two wrong statuses in a hand-maintained table, and the sibling
data-agent-service page records three numbers going stale in a single day for
exactly this reason. So the page ships with an em dash in every slot and fills
them from this file at load time.

WHAT IS IN HERE IS DERIVED, NEVER RESTATED. The member counts come from
`members.json`; the evidence figures come from the block
`scripts/render_evidence.py` generates into `docs/05-why-these-emulators.md`,
which in turn comes from azure-emulators' own checker. A source this cannot
parse is a hard failure, because a landing page that quietly drops a claim is
worse than a build that stops.
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "members.json"
EVIDENCE_DOC = ROOT / "docs" / "05-why-these-emulators.md"
MATRIX_DOC = ROOT / "docs" / "03-the-data-product-matrix.md"

# `| fabric | 113 | 107 | 0 | 6 | **107/113 (95%)** |`
EVIDENCE_ROW = re.compile(
    r"^\|\s*(\w+)\s*\|\s*(\d+)\s*\|.*\*\*(\d+)/(\d+)\s*\((\d+)%\)\*\*", re.M
)
FIGURES = re.compile(r"`revenue_usd ([\d,.]+)` across `([\d,]+)` sale")


def fail(what: str):
    raise SystemExit(
        f"site_data FAILED: could not read {what}.\n"
        f"  The landing page shows this as a claim, and publishing it blank or "
        f"stale is the failure this script exists to prevent."
    )


def build() -> dict:
    members = json.loads(REGISTRY.read_text(encoding="utf-8"))["members"]
    by_tier = {}
    for m in members:
        by_tier.setdefault(m["tier"], []).append(m)

    emulators = by_tier.get("emulator", [])
    platforms = by_tier.get("platform", [])
    if not emulators or not platforms:
        fail("emulator or platform members in members.json")

    doc = EVIDENCE_DOC.read_text(encoding="utf-8")
    rows = EVIDENCE_ROW.findall(doc)
    if not rows:
        fail(f"the evidence table in {EVIDENCE_DOC.name}")
    claims = sum(int(r[1]) for r in rows)
    pcts = sorted(int(r[4]) for r in rows)

    figures = FIGURES.search(MATRIX_DOC.read_text(encoding="utf-8"))
    if not figures:
        fail(f"the reproduced figures in {MATRIX_DOC.name}")

    return {
        "$comment": "Generated by scripts/site_data.py. Do not edit.",
        # Per emulator, so a card states its OWN evidence rather than the
        # family's best. Keyed by the short name the ledger uses.
        "evidence": {
            r[0]: {# r[2] is the numerator of the BOLD column (independently
            # evidenced), not the ci:-only column beside it. Named for what it
            # is: the first draft called it "external" and would have put 38
            # on keyvault's card where the ledger says 47.
            "claims": int(r[1]), "evidenced": int(r[2]), "pct": int(r[4])}
            for r in rows
        },
        "repos": len(members),
        "emulators": len(emulators),
        "bom": sum(1 for m in emulators if m.get("bom")),
        # The four that are not an analytics engine: identity, ARM, Key Vault,
        # APIM. Counted off `kind` rather than named, so a fifth lands here on
        # its own.
        "controlPlanes": sum(1 for m in emulators if m.get("kind") != "engine"),
        "cells": len(by_tier.get("leaf", [])),
        "engines": len({m["engine"] for m in platforms}),
        "orchestrators": len({m["orchestrator"] for m in platforms}),
        "applications": len(by_tier.get("application", [])),
        "claims": claims,
        "evidencedLow": pcts[0],
        "evidencedHigh": pcts[-1],
        "revenue": figures.group(1),
        "saleLines": figures.group(2),
    }


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out", type=Path, help="directory to write site-data.json into")
    args = p.parse_args()

    data = build()
    text = json.dumps(data, indent=2) + "\n"
    if args.out:
        args.out.mkdir(parents=True, exist_ok=True)
        (args.out / "site-data.json").write_text(text, encoding="utf-8")
        print(f"site_data: wrote {args.out / 'site-data.json'}")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
